# Generated by Django 3.1.4 on 2021-01-03 14:29

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tuition', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(regex='^([01]|\\+88)?\\d{11}')])),
                ('highest_education', models.CharField(max_length=200)),
                ('expected_salary', models.CharField(max_length=20)),
                ('current_tuition_status', models.CharField(choices=[('Available', 'Available'), ('Busy', 'Busy'), ('Deactivate', 'Deactivate')], max_length=12)),
                ('day_per_week', models.CharField(choices=[('1 day/week', '1 day/week'), ('2 day/week', '2 day/week'), ('3 day/week', '3 day/week'), ('4 day/week', '4 day/week'), ('5 day/week', '5 day/week'), ('6 day/week', '6 day/week'), ('7 day/week', '7 day/week')], max_length=12)),
                ('prefer_tutoring_style', models.CharField(choices=[('Online', 'Online'), ('Private', 'Private'), ('Coaching', 'Coaching'), ('Group', 'Group')], max_length=10)),
                ('place_of_learning', models.CharField(choices=[('class_room', 'Class Room'), ('Coaching_center', 'Coaching Center'), ('home_visit', 'Home Visit'), ('my_place', 'My Place')], max_length=19)),
                ('prefer_medium_tutor', models.CharField(choices=[('English', 'English'), ('Bangla', 'Bangla'), ('Arabic', 'Arabic'), ('Other', 'Other')], max_length=10)),
                ('prefer_class', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('Admission Test', 'Admission Test'), ('KG school', 'KG school'), ('Specific Skill Develop', 'Specific Skill Develop'), ('other', 'other')], max_length=50)),
                ('video_tutorial', models.URLField(blank=True, null=True)),
                ('prefer_area_to_teach', models.CharField(max_length=600)),
                ('prefer_district_to_teach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tuition.country')),
                ('prefer_subjects', models.ManyToManyField(related_name='subjects', to='tuition.Subject')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(default='avatar.png', upload_to='profile_pic')),
                ('birth_date', models.DateField()),
                ('religion', models.CharField(max_length=50)),
                ('fb_account', models.URLField(blank=True, null=True)),
                ('yt_channel', models.URLField(blank=True, null=True)),
                ('linkedin_pf', models.URLField(blank=True, null=True)),
                ('permanent_address', models.CharField(max_length=250)),
                ('experience', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
