# Generated by Django 3.1.4 on 2020-12-07 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TuitionPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=25)),
                ('class_other', models.CharField(max_length=100)),
                ('medium', models.CharField(choices=[('English', 'English'), ('Bangla', 'Bangla'), ('Arabic', 'Arabic'), ('Other', 'Other')], default='Bangla', max_length=7)),
                ('subjects', models.CharField(max_length=250)),
                ('school_college', models.CharField(max_length=500)),
                ('detail_tuition', models.TextField()),
                ('day_per_week', models.CharField(choices=[('1 day/week', '1 day/week'), ('2 day/week', '2 day/week'), ('3 day/week', '3 day/week'), ('4 day/week', '4 day/week'), ('5 day/week', '5 day/week'), ('6 day/week', '6 day/week'), ('7 day/week', '7 day/week')], default='3 day/week', max_length=10)),
                ('salary', models.CharField(max_length=50)),
                ('desire_tutor_gender', models.CharField(choices=[('g1', 'Male'), ('g2', 'Female'), ('g3', 'Other')], default='Male', max_length=5)),
                ('preference_tuition_style', models.CharField(choices=[('Online', 'Online'), ('Private', 'Private'), ('Coaching', 'Coaching'), ('Group', 'Group')], default='Private', max_length=8)),
                ('address', models.CharField(max_length=250)),
                ('mobile', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=50)),
                ('available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tuition.district')),
            ],
        ),
    ]
